Resources:
  queue276F7297:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: queue
    Metadata:
      aws:cdk:path: ServerlessCdkStack/queue/Resource
  table8235A42E:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: "N"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: ServerlessCdkStack/table/Resource
  publishFunctionServiceRole779A3536:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: ServerlessCdkStack/publishFunction/ServiceRole/Resource
  publishFunctionServiceRoleDefaultPolicy57B1EA19:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:SendMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - queue276F7297
                - Arn
        Version: "2012-10-17"
      PolicyName: publishFunctionServiceRoleDefaultPolicy57B1EA19
      Roles:
        - Ref: publishFunctionServiceRole779A3536
    Metadata:
      aws:cdk:path: ServerlessCdkStack/publishFunction/ServiceRole/DefaultPolicy/Resource
  publishFunction0955FBF8:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersa44123f02d6b08221ccc4eacd61d58196240301bea2a753beb040351dc51bdc0S3BucketC900D2F4
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa44123f02d6b08221ccc4eacd61d58196240301bea2a753beb040351dc51bdc0S3VersionKeyA7A355F0
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa44123f02d6b08221ccc4eacd61d58196240301bea2a753beb040351dc51bdc0S3VersionKeyA7A355F0
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - publishFunctionServiceRole779A3536
          - Arn
      Runtime: nodejs10.x
      Environment:
        Variables:
          QUEUE_URL:
            Ref: queue276F7297
    DependsOn:
      - publishFunctionServiceRoleDefaultPolicy57B1EA19
      - publishFunctionServiceRole779A3536
    Metadata:
      aws:cdk:path: ServerlessCdkStack/publishFunction/Resource
      aws:asset:path: /Users/n1527037/serverless-cdk/handlers/publish
      aws:asset:property: Code
  apiC8550315:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: api
    Metadata:
      aws:cdk:path: ServerlessCdkStack/api/Resource
  apiCloudWatchRoleAC81D93E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: ServerlessCdkStack/api/CloudWatchRole/Resource
  apiAccount57E28B43:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - apiCloudWatchRoleAC81D93E
          - Arn
    DependsOn:
      - apiC8550315
    Metadata:
      aws:cdk:path: ServerlessCdkStack/api/Account
  apiDeployment149F12949ccbca70e657894ed64e039dada00e6f:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: apiC8550315
      Description: Automatically created by the RestApi construct
    DependsOn:
      - apiGETECF0BD67
    Metadata:
      aws:cdk:path: ServerlessCdkStack/api/Deployment/Resource
  apiDeploymentStagedev96712F43:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: apiC8550315
      DeploymentId:
        Ref: apiDeployment149F12949ccbca70e657894ed64e039dada00e6f
      StageName: dev
    Metadata:
      aws:cdk:path: ServerlessCdkStack/api/DeploymentStage.dev/Resource
  apiGETApiPermissionServerlessCdkStackapi018B1A51GETD4367F72:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - publishFunction0955FBF8
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /
            - Ref: apiDeploymentStagedev96712F43
            - /GET/
    Metadata:
      aws:cdk:path: ServerlessCdkStack/api/Default/GET/ApiPermission.ServerlessCdkStackapi018B1A51.GET..
  apiGETApiPermissionTestServerlessCdkStackapi018B1A51GETB9F8FBB8:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - publishFunction0955FBF8
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /test-invoke-stage/GET/
    Metadata:
      aws:cdk:path: ServerlessCdkStack/api/Default/GET/ApiPermission.Test.ServerlessCdkStackapi018B1A51.GET..
  apiGETECF0BD67:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      RestApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - publishFunction0955FBF8
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: ServerlessCdkStack/api/Default/GET/Resource
  subscribeFunctionServiceRoleE1E26A6E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: ServerlessCdkStack/subscribeFunction/ServiceRole/Resource
  subscribeFunctionServiceRoleDefaultPolicyA1C1D645:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:ReceiveMessage
              - sqs:ChangeMessageVisibility
              - sqs:GetQueueUrl
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - queue276F7297
                - Arn
          - Action: dynamodb:PutItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - table8235A42E
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: subscribeFunctionServiceRoleDefaultPolicyA1C1D645
      Roles:
        - Ref: subscribeFunctionServiceRoleE1E26A6E
    Metadata:
      aws:cdk:path: ServerlessCdkStack/subscribeFunction/ServiceRole/DefaultPolicy/Resource
  subscribeFunction1FA97757:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersdb46d3739dade1c6f205c87b02748023b38f45a8e3544c01b542bbf1390b0254S3Bucket867E2CA8
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersdb46d3739dade1c6f205c87b02748023b38f45a8e3544c01b542bbf1390b0254S3VersionKey6EAA78B0
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersdb46d3739dade1c6f205c87b02748023b38f45a8e3544c01b542bbf1390b0254S3VersionKey6EAA78B0
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - subscribeFunctionServiceRoleE1E26A6E
          - Arn
      Runtime: nodejs10.x
      Environment:
        Variables:
          QUEUE_URL:
            Ref: queue276F7297
          TABLE_NAME:
            Ref: table8235A42E
    DependsOn:
      - subscribeFunctionServiceRoleDefaultPolicyA1C1D645
      - subscribeFunctionServiceRoleE1E26A6E
    Metadata:
      aws:cdk:path: ServerlessCdkStack/subscribeFunction/Resource
      aws:asset:path: /Users/n1527037/serverless-cdk/handlers/subscribe
      aws:asset:property: Code
  subscribeFunctionSqsEventSourceServerlessCdkStackqueue35EF96459007FD76:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn:
        Fn::GetAtt:
          - queue276F7297
          - Arn
      FunctionName:
        Ref: subscribeFunction1FA97757
    Metadata:
      aws:cdk:path: ServerlessCdkStack/subscribeFunction/SqsEventSource:ServerlessCdkStackqueue35EF9645/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.46.0,@aws-cdk/assets=1.46.0,@aws-cdk/aws-apigateway=1.46.0,@aws-cdk/aws-applicationautoscaling=1.46.0,@aws-cdk/aws-autoscaling-common=1.46.0,@aws-cdk/aws-cloudwatch=1.46.0,@aws-cdk/aws-dynamodb=1.46.0,@aws-cdk/aws-ec2=1.46.0,@aws-cdk/aws-events=1.46.0,@aws-cdk/aws-iam=1.46.0,@aws-cdk/aws-kms=1.46.0,@aws-cdk/aws-lambda=1.46.0,@aws-cdk/aws-lambda-event-sources=1.46.0,@aws-cdk/aws-logs=1.46.0,@aws-cdk/aws-s3=1.46.0,@aws-cdk/aws-s3-assets=1.46.0,@aws-cdk/aws-s3-notifications=1.46.0,@aws-cdk/aws-sns=1.46.0,@aws-cdk/aws-sns-subscriptions=1.46.0,@aws-cdk/aws-sqs=1.46.0,@aws-cdk/aws-ssm=1.46.0,@aws-cdk/cdk-assets-schema=1.46.0,@aws-cdk/cloud-assembly-schema=1.46.0,@aws-cdk/core=1.46.0,@aws-cdk/custom-resources=1.46.0,@aws-cdk/cx-api=1.46.0,@aws-cdk/region-info=1.46.0,jsii-runtime=node.js/v10.20.1
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersa44123f02d6b08221ccc4eacd61d58196240301bea2a753beb040351dc51bdc0S3BucketC900D2F4:
    Type: String
    Description: S3 bucket for asset "a44123f02d6b08221ccc4eacd61d58196240301bea2a753beb040351dc51bdc0"
  AssetParametersa44123f02d6b08221ccc4eacd61d58196240301bea2a753beb040351dc51bdc0S3VersionKeyA7A355F0:
    Type: String
    Description: S3 key for asset version "a44123f02d6b08221ccc4eacd61d58196240301bea2a753beb040351dc51bdc0"
  AssetParametersa44123f02d6b08221ccc4eacd61d58196240301bea2a753beb040351dc51bdc0ArtifactHash09A28989:
    Type: String
    Description: Artifact hash for asset "a44123f02d6b08221ccc4eacd61d58196240301bea2a753beb040351dc51bdc0"
  AssetParametersdb46d3739dade1c6f205c87b02748023b38f45a8e3544c01b542bbf1390b0254S3Bucket867E2CA8:
    Type: String
    Description: S3 bucket for asset "db46d3739dade1c6f205c87b02748023b38f45a8e3544c01b542bbf1390b0254"
  AssetParametersdb46d3739dade1c6f205c87b02748023b38f45a8e3544c01b542bbf1390b0254S3VersionKey6EAA78B0:
    Type: String
    Description: S3 key for asset version "db46d3739dade1c6f205c87b02748023b38f45a8e3544c01b542bbf1390b0254"
  AssetParametersdb46d3739dade1c6f205c87b02748023b38f45a8e3544c01b542bbf1390b0254ArtifactHash6FA7C616:
    Type: String
    Description: Artifact hash for asset "db46d3739dade1c6f205c87b02748023b38f45a8e3544c01b542bbf1390b0254"
Outputs:
  apiEndpoint9349E63C:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: apiC8550315
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: apiDeploymentStagedev96712F43
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

